apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  labels: 
    app: weather
spec:
  replicas: 3         # three pod
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: wpdlf/weather
        ports:
        - containerPort: 8000       # container port (pod port)
