apiVersion: v1
kind: Service
metadata:
  name: remoteapi
  labels: 
    run: remoteapi
spec:
  type: NodePort     # service type
  ports:
  - nodePort: 30800       # outer port
    port: 8080            # service port
    targetPort: 8000        # container port (pod port)
    protocol: TCP
  selector:
    app: remoteapi
  type: LoadBalancer
  externalIPs:
  - 54.180.188.168
